- name: Download kafka version {{ kafka_version }}
  ansible.builtin.get_url:
    url: "{{ kafka_url }}"
    dest: "/tmp/{{ kafka_archive }}.tar.gz"
    checksum: "{{ kafka_checksum }}"
    mode: "0644"

- name: Create kafka user
  user:
    name: "kafka"
    system: true

- name: Create kafka deploy directory
  ansible.builtin.file:
    path: "{{ kafka_deploy_directory }}"
    state: directory
    mode: "0750"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  become: true

- name: Create config directory
  ansible.builtin.file:
    path: "{{ kafka_config_dir }}"
    state: directory
    mode: "0750"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Create log directory
  become: true
  ansible.builtin.file:
    path: "{{ kafka_log_dirs }}"
    mode: "0750"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: directory

- name: Un-tar kafka download
  ansible.builtin.unarchive:
    src: "/tmp/{{ kafka_archive }}.tar.gz"
    dest: "{{ kafka_deploy_directory }}/"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    copy: false
    creates: "{{ kafka_deploy_directory }}/{{ kafka_archive }}"
  become: true

- name: Create kafka symlink
  ansible.builtin.file:
    src: "{{ kafka_deploy_directory }}/{{ kafka_archive }}/bin/"
    dest: /usr/bin/kafka
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: link

- name: Configure kafka server.properties
  ansible.builtin.template:
    src: "{{ kafka_mode }}.server.properties.j2"
    dest: "{{ kafka_config_dir }}/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0644"
  notify:
    - Restart kafka

- name: Copy kafka envfile
  ansible.builtin.template:
    src: kafka.env.j2
    dest: "{{ kafka_config_dir }}/kafka.env"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: "0644"
  notify:
    - Restart kafka

- name: Format Log Directories
  ansible.builtin.shell: /usr/bin/kafka/kafka-storage.sh format -t {{ kafka_cluster_id }} -c {{ kafka_config_dir }}/server.properties
  args:
    creates: "{{ kafka_log_dirs }}/meta.properties"
  when:
    kafka_mode == "kraft"

- name: Copy over systemd service file for kafka
  ansible.builtin.template:
    src: service.j2
    dest: /lib/systemd/system/kafka.service
    owner: root
    mode: 0644
  become: true


- name: Copy log4j config
  ansible.builtin.template:
    src: log4j.properties.j2
    dest: "{{ kafka_config_dir }}/log4j.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
  notify:
    - Restart kafka


- name: Start kafka systemd service
  systemd:
    name: kafka
    state: started
    daemon_reload: true
    enabled: true
  become: true
