---
- name: Download kafka version {{ kafka_version }}
  ansible.builtin.get_url:
    url: "{{ kafka_url }}"
    dest: "/tmp/{{ kafka_archive }}.tar.gz"
    checksum: "{{ kafka_checksum }}"
    mode: 0644

- name: Create kafka group
  ansible.builtin.group:
    name: "{{ kafka_group }}"
    system: true
    state: present

- name: Create kafka user
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    create_home: false
    system: true
    state: present

- name: Create log directory
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0750
  with_items: "{{ kafka_log_dirs }}"

- name: Unarchive kafka download
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/{{ kafka_archive }}.tar.gz"
    dest: "/opt/"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    creates: "/opt/{{ kafka_archive }}"

- name: Create kafka symlink
  ansible.builtin.file:
    src: "/opt/{{ kafka_archive }}"
    dest: "/opt/kafka"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    state: link

- name: Set kafka user home
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    home: "/opt/kafka"
    state: present

- name: Copy kafka server.properties
  ansible.builtin.template:
    src: "server.properties.j2"
    dest: "/opt/kafka/config/server.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0644
  notify:
    - Restart kafka

- name: Copy kafka environment
  ansible.builtin.template:
    src: "kafka.env.j2"
    dest: "/opt/kafka/config/kafka.env"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0644
  notify:
    - Restart kafka

- name: Format log directories
  ansible.builtin.command:
    argv:
      - "/opt/kafka/bin/kafka-storage.sh"
      - "format"
      - "-t"
      - "{{ kafka_cluster_id }}"
      - "-c"
      - "/opt/kafka/config/server.properties"
      - "--ignore-formatted"
  become: true
  become_user: kafka

- name: Copy kafka systemd service
  ansible.builtin.template:
    src: "systemd.service.j2"
    dest: "/usr/lib/systemd/system/kafka.service"
    owner: "root"
    group: "root"
    mode: 0644

- name: Copy log4j config
  ansible.builtin.template:
    src: "log4j.properties.j2"
    dest: "/opt/kafka/config/log4j.properties"
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: 0644
  notify:
    - Restart kafka

- name: Flush handlers to prevent restart after start
  ansible.builtin.meta: flush_handlers

- name: Start kafka
  ansible.builtin.systemd:
    name: kafka
    state: started
    daemon_reload: true
    enabled: true
