---
- name: Reload systemctl daemon
  ansible.builtin.systemd:
    daemon_reexec: yes
  when: ansible_service_mgr == 'systemd'

- name: Restart kafka
  ansible.builtin.systemd:
    name: kafka
    state: restarted
